# Generated by Django 3.2.5 on 2021-09-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserCredentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncredentials',
            name='procore_company_id',
        ),
    ]
