# Generated by Django 3.2.5 on 2021-09-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserCredentials', '0002_remove_productioncredentials_procore_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_procore_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_procore_app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_procore_redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_procore_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_procore_app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_procore_redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_qbo_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_qbo_app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_qbo_redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_qbo_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_qbo_app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_qbo_redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sandbox_active', models.BooleanField(default=False)),
                ('is_prod_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sandboxcredentials',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductionCredentials',
        ),
        migrations.DeleteModel(
            name='SandboxCredentials',
        ),
    ]
