# Generated by Django 3.2.5 on 2021-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0002_auto_20210730_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='quickbook_realmid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
