# Generated by Django 3.2.5 on 2021-08-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleAppOAuth2', '0006_syncvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCostCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date_time', models.DateTimeField(auto_now_add=True)),
                ('biller_id', models.IntegerField(blank=True, null=True)),
                ('costcode_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('biller', models.CharField(blank=True, max_length=255, null=True)),
                ('qbo_cost_code_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
