# Generated by Django 3.2.5 on 2021-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0010_syncexpenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncprojects',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='syncexpenses',
            name='procore_project_id',
        ),
        migrations.RemoveField(
            model_name='syncexpenses',
            name='procore_vendor_id',
        ),
        migrations.AddField(
            model_name='syncexpenses',
            name='procore_project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='syncexpenses',
            name='procore_vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
