# Generated by Django 3.2.5 on 2021-08-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleAppOAuth2', '0011_auto_20210822_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOwnerInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date_time', models.DateTimeField(auto_now_add=True)),
                ('procore_owner_invoice_id', models.IntegerField(blank=True, null=True)),
                ('qbo_customer_invoice_id', models.IntegerField(blank=True, null=True)),
                ('procore_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
