# Generated by Django 3.2.5 on 2021-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0012_syncownerinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncownerinvoices',
            name='is_synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncownerinvoices',
            name='procore_owner_invoice_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncownerinvoices',
            name='qbo_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncownerinvoices',
            name='qbo_customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
