# Generated by Django 3.2.5 on 2021-09-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleAppOAuth2', '0013_auto_20210831_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractorInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date_time', models.DateTimeField(auto_now_add=True)),
                ('procore_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('procore_sbc_invoice_no', models.IntegerField(blank=True, null=True)),
                ('procore_invc_amount', models.FloatField(blank=True, null=True)),
                ('qbo_vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qbo_vendor_id', models.IntegerField(blank=True, null=True)),
                ('qbo_amount', models.FloatField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
