# Generated by Django 3.2.5 on 2021-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0014_subcontractorinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractorinvoices',
            name='procore_sbc_invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
