# Generated by Django 3.2.5 on 2021-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0016_syncownerinvoices_procore_prime_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncownerinvoices',
            name='procore_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
