# Generated by Django 3.2.5 on 2021-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0017_syncownerinvoices_procore_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='procore_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
