# Generated by Django 3.2.5 on 2021-09-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0018_authtoken_procore_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synccostcodes',
            old_name='biller',
            new_name='full_code',
        ),
        migrations.RenameField(
            model_name='synccostcodes',
            old_name='biller_id',
            new_name='parent_id',
        ),
    ]
