# Generated by Django 3.2.5 on 2021-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0020_schedulingsynchronizing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingsynchronizing',
            name='last_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedulingsynchronizing',
            name='next_schedule',
            field=models.DateTimeField(blank=True),
        ),
    ]
