# Generated by Django 3.2.5 on 2021-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0022_auto_20211008_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulingsynchronizing',
            old_name='next_schedule',
            new_name='schedule_date_time',
        ),
        migrations.AlterField(
            model_name='schedulingsynchronizing',
            name='user_sync_frequency_choices',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=12, null=True),
        ),
    ]
