# Generated by Django 3.2.5 on 2021-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0023_auto_20211008_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingsynchronizing',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulingsynchronizing',
            name='schedule_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
