# Generated by Django 3.2.5 on 2021-10-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0024_auto_20211008_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulingSynchronizing',
        ),
    ]
