# Generated by Django 3.2.5 on 2021-10-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0025_delete_schedulingsynchronizing'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='user_encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
