# Generated by Django 3.2.5 on 2021-10-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0027_syncusertasks_taskchoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchoices',
            name='name',
        ),
        migrations.AddField(
            model_name='taskchoices',
            name='tasks',
            field=models.CharField(choices=[('PROJECTS', 'PROJECTS'), ('VENDORS', 'VENDORS'), ('COST-CODE', 'COST CODES'), ('CUSTOMER-INV', 'CUSTOMER INVOICES'), ('SUB-CONTRACTOR-INV', 'SUB-CONTRACTOR INVOICES'), ('CUSTOMER-PAYMENTS', 'CUSTOMER PAYMENTS'), ('SUB-CONTRACTOR-PAYMENTS', 'SUBCONTRACTOR PAYMENTS'), ('EXPENSE', 'EXPENSES')], max_length=25, null=True),
        ),
    ]
