# Generated by Django 3.2.5 on 2021-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAppOAuth2', '0028_auto_20211015_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='procore_access_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='procore_refresh_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='quickbook_access_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='quickbook_refresh_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
