QBO_MINOR_VERSION = "62"
# PROCORE developer app settings for making requests
SANDBOX_PROCORE_OAUTH_URL = "https://login-sandbox.procore.com/"
SANDBOX_PROCORE_BASE_URL = "https://sandbox.procore.com/"
PROD_PROCORE_OAUTH_URL = "https://login.procore.com/"
PROD_PROCORE_BASE_URL = "https://api.procore.com/"
BASE_URL_PROJECT = "http://ec2-3-98-94-161.ca-central-1.compute.amazonaws.com:8000/app/"
PASSWORD_SECRET_KEY = '6322aec6f64b6cb499c629408cacf54e9788a17957502fddb71dfafbb998b1f2'
SYNC_PROJECT_CHOICE_KEY = 1
SYNC_VENDOR_CHOICE_KEY = 2
SYNC_COST_CODE_CHOICE_KEY = 3
SYNC_CUSTOMER_INVOICES_CHOICE_KEY = 4
SYNC_SUB_CONTRACTOR_INVOICES_CHOICE_KEY = 5
SYNC_CUSTOMER_PAYMENTS_CHOICE_KEY = 6
SYNC_SUB_CONTRACTOR_PAYMENTS_CHOICE_KEY = 7
SYNC_EXPENSE_CHOICE_KEY = 8
